---
title: "ESM204HW4"
author: "Robert Saldivar"
date: "June 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Loading Packages and Data

library(tidyverse)
library(RColorBrewer)

Data <- read_csv("HW4Data.csv")
```

*Question 1*

```{r}
#Exploring data
MCA_graph <- ggplot(Data, aes(x = Abatement, y = MC_A)) + 
  geom_point()+
  theme_bw() +
  geom_smooth(method = lm, se = TRUE, size = 0.6, color = "grey")+
  scale_x_continuous()

MCB_graph <- ggplot(Data, aes(x = Abatement, y = MC_B)) + 
  geom_point()+
  theme_bw() +
  geom_smooth(method = lm, se = TRUE, size = 0.6, color = "grey")+
  scale_x_continuous()

MCC_graph <- ggplot(Data, aes(x = Abatement, y = MC_C)) + 
  geom_point()+
  theme_bw() +
  geom_smooth(method = lm, se = TRUE, size = 0.6, color = "grey")+
  scale_x_continuous()

MCD_graph <- ggplot(Data, aes(x = Abatement, y = MC_D)) + 
  geom_point()+
  theme_bw() +
  geom_smooth(method = lm, se = TRUE, size = 0.6, color = "grey")+
  scale_x_continuous()

MCA_graph
MCB_graph
MCC_graph
MCD_graph
```

```{r}
#Running Linear Regressions

MCA_lm <- lm(MC_A ~ Abatement, data = Data)
MCB_lm <- lm(MC_B ~ Abatement, data = Data)
MCC_lm <- lm(MC_C ~ Abatement, data = Data)
MCD_lm <- lm(MC_D ~ Abatement, data = Data)

summary(MCA_lm)
summary(MCB_lm)
summary(MCC_lm)
summary(MCD_lm)
```

*Question 2*

```{r}
#Deriving a price all regions are willing to pay for polluting

MC_A_Price <- MCA_lm$coefficients[1] + MCA_lm$coefficients[2]*180

MC_B_Price <- MCB_lm$coefficients[1] + MCB_lm$coefficients[2]*200

MC_C_Price <- MCC_lm$coefficients[1] + MCC_lm$coefficients[2]*220

MC_D_Price <- MCD_lm$coefficients[1] + MCD_lm$coefficients[2]*300

```

```{r}
#Deriving the demand curve for all regions

MBA_slope <- (MC_A_Price - 0)/(0-180)

MBB_slope <- (MC_B_Price - 0)/(0-200)

MBC_slope <- (MC_C_Price - 0)/(0-220)

MBD_slope <- (MC_D_Price - 0)/(0-300)


```

```{r}
seq_a <- seq(from = 0, to = 180)%>%
  as.data.frame()
colnames(seq_a)<-"pollution"

pol_price_unit_a <- seq_a %>%
  mutate(pollution, pollution*MBA_slope+MC_A_Price)
colnames(pol_price_unit_a) <- c("pollution", "MWP_A")

seq_b <- seq(from = 0, to = 200)%>%
  as.data.frame()
colnames(seq_b)<-"pollution"

pol_price_unit_b <- seq_b %>%
  mutate(pollution, pollution*MBB_slope+MC_B_Price)
colnames(pol_price_unit_b) <- c("pollution", "MWP_B")

seq_c <- seq(from = 0, to = 220)%>%
  as.data.frame()
colnames(seq_c)<-"pollution"

pol_price_unit_c <- seq_c %>%
  mutate(pollution, pollution*MBC_slope+MC_C_Price)
colnames(pol_price_unit_c) <- c("pollution", "MWP_C")

seq_d <- seq(from = 0, to = 300)%>%
  as.data.frame()
colnames(seq_d)<-"pollution"

pol_price_unit_d <- seq_d %>%
  mutate(pollution, pollution*MBD_slope+MC_D_Price)
colnames(pol_price_unit_d) <- c("pollution", "MWP_D")



```

```{r}
#Creating Graph for the Demand curves

Demand_A <- ggplot(pol_price_unit_a, aes(x= pollution, y = MWP))+
  geom_line()+
  theme_bw() +
  scale_x_continuous(limits=c(0,310)) +
  scale_y_continuous(limits=c(0,180))
  
Demand_B <- ggplot(pol_price_unit_b, aes(x=pollution, y= MWP))+
  geom_line() +
  theme_bw() +
  scale_x_continuous(limits=c(0,310)) +
  scale_y_continuous(limits=c(0,180))

Demand_C <- ggplot(pol_price_unit_c, aes(x=pollution, y= MWP))+
  geom_line() +
  theme_bw() +
  scale_x_continuous(limits=c(0,310)) +
  scale_y_continuous(limits=c(0,180))

Demand_D <- ggplot(pol_price_unit_d, aes(x=pollution, y= MWP))+
  geom_line()+
  theme_bw() +
  scale_x_continuous(limits=c(0,310)) +
  scale_y_continuous(limits=c(0,180))

Demand_A
Demand_B
Demand_C
Demand_D
```

*Question 3a*

```{r}
#Creating aggrigate cost curve for country x
Abatement_Cost_ab <- full_join(pol_price_unit_a, pol_price_unit_b, by ="pollution")

Abatement_Cost_ab[is.na(Abatement_Cost_ab)] <- 0

Abatement_Cost_abc <- full_join(Abatement_Cost_ab, pol_price_unit_c, by = "pollution") 

Abatement_Cost_abc[is.na(Abatement_Cost_abc)] <- 0

Aggrigate_Cost_X <- Abatement_Cost_abc %>%
  mutate(Aggrigate =(MWP_A+MWP_B+MWP_C))

```

```{r}
#Visualizaing the aggrigate demand curve

Ag_demand_curve_x <- ggplot(Aggrigate_Cost_X, aes(x=pollution)) +
  geom_line(aes(y=Aggrigate), color = "red") +
  geom_line(aes(y=MWP_A), color = "green") +
  geom_line(aes(y=MWP_B), color = "blue") +
  geom_line(aes(y=MWP_C), color = "purple") +
  theme_bw() +
  labs(x= "Cabon Emission", y="Marginal Benefit of Carbon Emisson ($/ton)")


Ag_demand_curve_x
```

